quasar-team/quasar

.travis.yml
Configuration/CMakeLists.txt
Configuration/Configurator.h
Configuration/designToConfigurator.xslt
Server/include/BaseQuasarServer.h
Server/src/BaseQuasarServer.cpp

Pull request to merge the user defined configuration extension to the trunk

User defined configuration extension

---

Design/designValidation.xslt

Implemented in the design validator.

OPCUA-1036 isKey doesn't work without device logic and with arrays

---

Meta/src/meta.cpp

Small change this one - turning a todo into a done.
https://its.cern.ch/jira/browse/OPCUA-1141
Tested: results of a trial mis-configuration posted in the JIRA ticket above.

replace abort call in meta.cpp with exception

---

AddressSpace/designToAddressSpaceDocHtml.xslt
Design/Design.xsd
Documentation/quasarCommands.html
FrameworkInternals/quasarCommands.py
FrameworkInternals/transformDesign.py

New functionality for generation of address space documentation.

Implemented OPCUA-1139 and OPCUA-1151

---

Meta/src/Base_DComponentLogLevel.cpp
Meta/src/Base_DGeneralLogLevel.cpp
Meta/src/Base_DQuasar.cpp
Meta/src/Base_DServer.cpp
Meta/src/Base_DSourceVariableThreadPool.cpp
Meta/src/Base_DStandardMetaData.cpp
Meta/src/DQuasar.cpp
Meta/src/DServer.cpp
Meta/src/DSourceVariableThreadPool.cpp
Meta/src/DStandardMetaData.cpp

Ready to go, no surprises in here I think.

removed headers for boost foreach - range based for instead

---

.travis.yml
CMakeLists.txt
FrameworkInternals/commandMap.py

Tested on a simple server with open6 backend, did fine.

OPCUA-183 cmake3

---

Documentation/quasarCommands.html
FrameworkInternals/manage_files.py
FrameworkInternals/quasarCommands.py

https://its.cern.ch/jira/browse/OPCUA-1211

Implemented OPCUA-1211

---

AddressSpace/designToClassBody.xslt

ArrayDimensions attribute will be set.
In future we can think how to also propagate array dimensions restrictions from Design.

Implemented setting arrayDimensions for arrays

---

Configuration/designToConfigDocumentationHtml.xslt
Configuration/designToConfigurationXSD.xslt
Design/Design.xsd
Design/designValidation.xslt

Taken care of the following aspects:
* Design schema,
* propagation to Config schema,
* Design Validation (2nd stage validator),
* Config documentation
Everything should be backwards-compatible.

Implemented default values of config entries

---

Meta/include/ASServer.h
Meta/include/DServer.h
Meta/include/MetaUtils.h
Meta/src/ASServer.cpp
Meta/src/DServer.cpp
Meta/src/MetaUtils.cpp
Server/include/QuasarServerCallback.h
Server/src/QuasarServerCallback.cpp

https://its.cern.ch/jira/browse/OPCUA-1487

Removed connectedClientCount

---

CalculatedVariables/src/CalculatedVariablesEngine.cpp

So now we review the support for $thisObjectAddress (i.e. same as $_ ) and $parentObjectAddress,
both were already successfully tested.

Opcua 1497 varied level parents

---

FrameworkInternals/manage_files.py
FrameworkInternals/version_control_interface.py
appveyor.yml

What do you think folks? Fixes the windows build inline with python3. Only contentious issue might be me replacing `variable_value is test_value` which I understand is actually an _identity_ (same object) test with `variable_value == test_value` which is an equality test.
I like mine better. But then I would say that.

Opcua 1610 python3 appveyor build

---

FrameworkInternals/manage_files.py

Naive migration to Python3 made it non-working in Python2.x, BUT
either way we always wanted to improve it (yet in Damian's times).
So here it comes.

OPCUA-1630 subprocess getstatusoutput

---

Server/include/opcserver_open62541.h
Server/src/opcserver_open62541.cpp

Hi,
this is generally related to OPCUA-1644 from open62541-compat.
It follows the move of UA_Server business from quasar to open62541-compat, so quasar becomes independent of open62541 internals related to UA_Server.
OPCUA-1644 was already reviewed and was released as open62541-compat 1.1.5

quasar-side of OPCUA-1642 implemented

---

open62541_config.cmake
open6_win_configuration.cmake

Ready to go, windows and linux

Opcua 1657 fix windows and linux ci builds on master

---

appveyor.yml

add missing variable to PATH

---

Server/src/BaseQuasarServer.cpp

Includes:
```
--config_file             
--opcua_backend_config    
--create_certificate
--help, -h
--version, -v
```

allowing single letter program options

---

Configuration/designToConfigurationXSD.xslt

https://its.cern.ch/jira/browse/OPCUA-1686

Fixed, now the length must be minimum 1

---

CalculatedVariables/src/CalculatedVariablesEngine.cpp

Description of the problem being solved:
https://its.cern.ch/jira/browse/OPCUA-1726

Capture group now finishes with encountering a parenthesis... (extended \S catch)

---

CalculatedVariables/src/CalculatedVariablesEngine.cpp

Problem which is being solved is described in:
https://its.cern.ch/jira/browse/OPCUA-1687

Now the formula replacement is partial instead of complete

---

Configuration/designToConfigurator.xslt

details under
https://its.cern.ch/jira/browse/OPCUA-1683

Silencing unused variable warning

---

FrameworkInternals/manage_files.py

I suggest to view it with whitespace changes turned off:
https://github.com/quasar-team/quasar/pull/179/files?diff=unified&w=1

Fix for OPCUA-1863

---

AddressSpace/include/ASNodeManager.h
AddressSpace/templates/designToClassHeader.jinja

Mostly cosmetic improvements noticed on Jinja conversion.

Removed UA_DISABLE_COPY from AS Headers and from ASNodeManager

---

Design/templates/designToDot.jinja

The problem (fixed here) prevents certain types of classes to be visualised correctly.

Logical condition handled in the other branch

---

FrameworkInternals/BoostSetup.cmake
Server/include/BaseQuasarServer.h
Server/src/BaseQuasarServer.cpp

Here we go - ready for review. There's some sample output on https://its.cern.ch/jira/browse/OPCUA-2041 ticket.

Opcua 2041 log startup information

---

FrameworkInternals/manage_files.py
FrameworkInternals/quasarCommands.py
FrameworkInternals/version_control_interface.py

I will introduce this feature on the next quasar mtng but have an earlier coup d'oeil if you have time.

OPCUA-2138 project wise astyle

---

Configuration/templates/designToConfigDocumentationHtml.jinja
FrameworkInternals/Oracle.py

This fixes printing of config restrictions which I accidentally broke when Pythonizing the way in which restrictions are represented.

Fixing restriction values

---

.CI/test_cases/test_default_quasar_design/reference_ns2.xml
.travis.yml

Please read the email on quasar-developers from Friday evening for the description ;-)

OPCUA-2257 node set compare primer

---

Documentation/source/CalculatedVariables.rst

applied some corrections

---

Documentation/source/quasar.rst

Information about necessary EPEL dependencies included in the documentation

Adding missiing information about EPEL dependencies

---

CalculatedVariables/include/CalculatedVariable.h
CalculatedVariables/src/CalculatedVariable.cpp
Documentation/source/CalculatedVariables.rst

This PR introduces enhancements to the update mechanism of Calculated Variables and includes an update to the relevant documentation.
Please review and provide your feedback.

Opcua 3040 calculated variables per request

---

Documentation/source/UserDefinedCommandLineParameters.rst
Documentation/source/UserDefinedRuntimeConfigurationModification.rst

Modified UserDefinedCommandLineParameters.rst and UserDefinedRuntimeConfigurationModification.rst files to fix code format for example code.

Quasar documentation fixup

---

Meta/src/metaBackwardsCompatibilityUtils.cpp

all context described in ticket OPCUA-3263

merge to master for OPCUA-3263-use-content-order-id-aware-clear
