FrameworkInternals/files.txt
FrameworkInternals/original_files.txt
LogIt/CMakeLists.txt
LogIt/include/BoostRotatingFileLog.h
LogIt/include/LogIt.h
LogIt/include/LogItInstance.h
LogIt/include/LogSinks.h
LogIt/src/BoostRotatingFileLog.cpp
LogIt/src/LogIt.cpp
LogIt/src/LogItInstance.cpp
LogIt/src/LogRecord.cpp
LogIt/src/LogSinks.cpp

From the JIRA item:
Observed behaviour on windows:
When using dynamically loaded libraries (dlls), for example, LogIt calls to log messages does not work. Specifically this was noticed during the course of the work involving the 'CAN Common Component', which loads so/dll libraries containing implementation code for a specific CAN gateway.

Log it with dll support [OPCUA-608]

---

Meta/src/Base_DComponentLogLevel.cpp

Fix for OPCUA-611, initialize uninitialized variable - stops call to abort() on startup. Only affects debug builds.

[OPCUA-611] Fix for debug builds sometimes stopping with abort() call

---

Server/src/shutdown.cpp

Fixed a bug in shutdown.cpp (file provided by unified automation) in which, in some version of windows, if a set of specific conditions is met, windows.h will not be included and the file will fail to compile, since it is needed to resolve the variable MAX_PATH.
In the bugfix, windows.h will be included if the macro WIN32 exists (ergo, the system is a windows machine).
Bug defined in jira issue OPCUA-616.

Bugfix in shutdown.cpp (file provided by unified automation)

---

Documentation/quasar.html
Server/src/opcserver.cpp
Server/src/serverconfigxml.cpp

The previous fix (uatoolkit_14x branch) was supposed to work with 1.3.x, 1.4.x and 1.5.x API, however it turned out that preprocessor defines carrying version information have been renamed in 1.5.x API.
Therefore now, in case "old" defines are not found, "new" ones are used to evaluate SDK version.
I tested this personally with 1.5.1 evaluation version and *don't expect* backward issues with former versions.

Fix for UA API 1.5.x

---

FrameworkInternals/original_files.txt
Server/CMakeLists.txt
Server/include/BaseQuasarServer.h
Server/include/opcserver.h
Server/include/opcserver_open62541.h
Server/src/BaseQuasarServer.cpp
Server/src/opcserver.cpp
Server/src/opcserver_open62541.cpp

The purpose is simplification and removal of backend-specific things in BaseQuasarServer class. Almost all backend-specific things were moved to OpcServer (existing previously) but now 2 implementations exist (one per each  backend).
This cleanup reduced number of ifdefs from 19 to 5 in cpp file, and also few in the header file.
The philosophy is similar to open62541-compat module: open62541-compatible implementation was provided for UA API OpcServer interface.

OPCUA-653 reduce ifdefs

---

README.md

Hi All,
Now that the linux and windows CI builds have been restored (and passing!) we should add the build status flags to our readme. Looks like this
Change only affects the readme.md - Piotr, if you like the look of this then please just merge this in.
Cheers,
Ben

Add ci build tags to readme

---

.travis.yml
open62541_config.cmake

Moved the build from the native travis node (where build problems are almost impossible to debug) to a public docker image which is easy to debug (install docker locally, pull the image and run the same commands as travis runs from the .travis.yml script)
Latest image cached in docker.com
https://hub.docker.com/r/bfarnham/quasar/tags/
Image built from this docker file
https://github.com/quasar-team/docker/blob/master/CC7_Open62541/Dockerfile

Travis with docker

---

.travis.yml

The changes are to follow new convention of "open62541-compat" deployment.
It passed travis build:
https://travis-ci.org/quasar-team/quasar/builds/168867625

Travis uses open62541-compat deployment

---

AddressSpace/designToClassBody.xslt
Configuration/designToConfigurationXSD.xslt
Design/CommonFunctions.xslt
Design/Design.xsd

The feature was tested with a cache variable in both directions - reading and writing - from OPC-UA client.

Adding ByteStream to supported data types

---

appveyor.yml
open6_win_configuration.cmake

Sigh, still finding and cleaning up unpleasant findings in the windows CI build. Some my fault, too hasty a job done I think. Still, the situation is the situation and here are 2 options for reaching the light at the end of the windows CI build tunnel (and let's hope the light is not a train coming).
==option 1==
To get a passing windows CI build in the _pnikiel_methods_ quasar branch before it is merged to master the following needs to happen...
1. Merge the **open62541-compat** [pull request #9](https://github.com/quasar-team/open62541-compat/pull/9) to master. This makes an open62541-compat module in the **master** branch that once again builds on windows. It should have always been like that, I failed to notice a static tag in the windows CI build instructions, so the open62541-compat …

Use optional modules in windows ci build

---

Server/src/opcserver.cpp

Apparently, in UA SDK 1.5.5, in order to just created PKI certificate repo, one has to do more than just loading the configuration, compared to UA SDK 1.3.3. 
This fix should address it; in addition I migrated few "cout" logs to LogIt.
Tested with UA SDK 1.3.3 and UA SDK 1.5.5.
Compare whitespace-insensitive:
https://github.com/quasar-team/quasar/pull/35/files?w=1

Fix for certificate creation for toolkit 1.5.5

---

.travis.yml
open62541_config.cmake

Required as a consequence (actually a benefit) of the merge just carried out in open62541-compat.

CI builds no longer use python to setup open6

---

AddressSpace/designToSourceVariablesBody.xslt
AddressSpace/designToSourceVariablesHeader.xslt
Common/CMakeLists.txt
Common/include/QuasarThreadPool.h
Common/src/QuasarThreadPool.cpp
Common/test/test_quasar_threadpool.cpp
Design/Design.xsd
FrameworkInternals/original_files.txt
Server/src/BaseQuasarServer.cpp

There is an issue with UASDK ThreadPool: it has a fixed maximum task/thread factor of 4. This prevents some classes of applications, e.g. where a very big number of requests have to be accepted at one given moment. 
After a brief consideration of boost::asio threadpool, I rolled out this one. It is past initial tests where I managed to submit 50000 requests distributed into varied number of threads. Seems fine so far but will be additionally tested, of course.
What's missing: the maximum number of requests of source variables is not exposed in the config yet. So far hardcoded. Requires some changes of Meta.

Quasar Thread Pool, and its application to source variables

---

Meta/include/Certificate.h
Meta/src/Certificate.cpp

1. Removes "using namespace" from the header not to pollute the namespace,
2. Fixes memory initialization by memset
3. Throws in case of logic error with Certificate::Instance rather than logs it (it would most likely trigger a null ptr exception or so)

Opcua 1056 improve memory management certificate

---

README.md
appveyor.yml

Strange. Apparently the CI build nodes used by quasar are (today) barfing on some old version of python pip. However, this was not a problem on Friday (when the quasar master branch built fine). Added a pip upgrade to the yml file.
Also added link to the appvyor/travis build for the master branch to the build badge displayed on the READMD.md

Fix python pip error in windows ci build

---

Device/designToDeviceBaseHeader.xslt

The reason of exposing device logic mutex (when it is declared in the Design of course) is to enable RAII-style constructs like:
std::lock_guard<decltype( getLock())> lock (getLock());

Implemented and tested

---

AddressSpace/CMakeLists.txt
Configuration/CMakeLists.txt
Device/CMakeLists.txt
Documentation/ChangeLog.html
Meta/CMakeLists.txt

The reason for such a change is that the target was named exactly as the file it generates (which was not the most optimal decision), and that confused "ninja" builder.

OPCUA-1061 rename configurationhxx target

---

AddressSpace/CMakeLists.txt
AddressSpace/designToGeneratedCmakeAddressSpace.xslt
CMakeLists.txt
Configuration/CMakeLists.txt
Configuration/designToConfigurationXSD.xslt
Device/CMakeLists.txt
Device/designToGeneratedCmakeDevice.xslt
FrameworkInternals/configurationGenerators.py
FrameworkInternals/externalToolCheck.py
FrameworkInternals/generateCmake.py
FrameworkInternals/quasarExceptions.py
FrameworkInternals/transformDesign.py
quasar.py

This is the full-featured out-of-source build capability.
The last PR #61 equipped individual quasar generators to understand --project_binary_dir, this PR benefits from it via update CMake statements.
The end-user advantage is that they can do:
./quasar build --project_binary_dir   <somewhere>
and given quasar server should be build in <somewhere> without polluting the source directory.

Merge-back the out-of-source

---

CMakeLists.txt
ProjectSettings.cmake

The motivation to this is to have an option to build a (complete) quasar-based server as a shared object. This is required to load it, run it (and do data exchange with it) from a higher-level programming language like Python or so.

Implemented shared object creation

---

Server/include/BaseQuasarServer.h

Let external classes access node managers (relevant e.g. for embedding quasar into Python)

---

appveyor.yml

Hum, not a fix per-se. More of a patch. Enough to get us past the current CI build blocker.
The long term solution is to move away from the vagaries of machine provisioning on appveyor on every build (the source of most of our problems) to a more stable windows build platform in the form of a windows docker image. That's a work in progress (it's quite a lot harder than I'd thought - much harder than linux images).
I'd suggest merging this to master, it should keep the CI build running for now.

Appveyor build fix

---

CalculatedVariables/src/CalculatedVariablesChangeListener.cpp

This is relevant to all situations when a calc var is created on a hardware-polled value which can be NULL e.g. because of connectivity malfunction or so. In such a case WRN was too much for a log level.

Implemented better handling when Variant is Null;

---

Device/designToDeviceBaseBody.xslt
Device/designToDeviceBaseHeader.xslt

This was planned for ages...
Device classes should use getAddressSpaceLink() instead of m_addressSpaceLink,
this is especially important for code that gets executed at init or at destruction (especially if that code was spawned from an extra thread) because the risk of nullptr dereference is minimized.

Made m_addressSpaceLink private

---

Device/designToDeviceBaseHeader.xslt

It was found out that for long time we had that issue that the body of the member function was generated, but it was not in the headers... now it is fixed!

Implemented missing header

---

Configuration/CMakeLists.txt
Configuration/designToConfigurator.xslt

Adding manual defines does not seem necessary as passing correct options to xsd-cxx places the defintion in the respective header.

Opcua 1623 quasar fails to compile in c++17 mode

---

Meta/CMakeLists.txt

The problem we're solving is that in my case OPCUA_LIBS are (in CMake): -lrt -lpthread, that is, no static or dynamic lib as that is no longer necessary.
So they get passed as
meta_build_info.py --project_root_dir /tmp/check_bundled_open62541 --target_generation_dir /tmp/check_bundled_open62541/build/generated --toolkit_libs -lrt;-lpthread
where -lrt is read as an argument to python and not as an argument that was/would be used for the linker.
You can try yourself, it is easy to reproduce.
I propose to replace -l by _l, I know -- quite weak -- for the moment works but for sure will break one day. Maybe we can do this improvement now and then you contribute sth better in near future?

meta_build_info, problem of escaping toolkit_libs

---

FrameworkInternals/transform_filters.py

Example:
{{debug("WARNING: Skipping array cache-variable. There is no support for arrays in Cacophony yet.",
"(at class:", class_name, " cache-variable: ", cv.get('name'))}}
so not as a filter but as a funcion
it is 100% backwards-compat
and this one is much better to put more debugging arguments which can be literally of any type

Debug can now be used as Jinja2 function and not only filters

---

.CI/travis/job_prologue.sh
.travis.yml

Hi All,
So this is ready to go. Reviews welcome.
Bit of a complicated PR this one. Merge to master requires
1. In file .travis.yml change tag from 'quasar-open62541-next' to 'quasar-open62541' (done to separate previous docker image and new docker image).
2. push docker image currently known as 'docker.io/bfarnham:quasar-open62541-next' --> 'docker.io/bfarnham:quasar-open62541'.
3. merge quasar-team/docker PR containing changes to dockerfile (https://github.com/quasar-team/docker/pull/13)

updated to work on latest open6 docker.io image

---

.travis.yml

Last part of OPCUA-2005. Had updated the images and pushed tagged image to docker.io, but then forgot to retag at docker.io with 'quasar-open62541'.
Now fixed docker.io tag (so latest CI image is 'quasar-open62541'), which requires these changes in the travis yml file

use image docker.io/bfarnham/quasar:quasar-open62541

---

FrameworkInternals/transformDesign.py

Who wants a coup d'oeil on it?
CI results:
test name                                | ret code | time spent [s] 
---------------------------------------- + -------- + ---------------
open62541_default_quasar_design          |        0 |             136
open62541_test_recurrent_hasobjects      |        0 |             137
open62541_test_cache_variables           |        0 |             212
open62541_test_single_variable_node      |        0 |             137
open62541_test_methods                   |        0 |             139
open62541_test_instantiation_from_design |        0 |             124
open62541_test_config_entries            |        0 |             136
open62541_test_config_restrictions       |        0 |             136
uasdk_default_quasar_design              |        0 | …

Opcua 2176 detect too old astyle

---

AddressSpace/include/ArrayTools.h

ArrayTools error when compiling with newer g++

fix for missing library

---

Common/include/Utils.h
FrameworkInternals/original_files.txt
Server/CMakeLists.txt
Server/include/OpcuaToolkitInfo.hpp.in
Server/src/BaseQuasarServer.cpp

This contribution includes OPCUA-2757 and further adds the OPCUA toolkit path at the time of the compilation and all the information that UASDK provides as "extra" with a separate arg (for hackers only).
Please consider only this PL as the one representing both 2757+2758.

OPCUA-2758 Toolkit path + extra info

---

quasar.py

Colorama function to ensure ANSI escapes handled properly on windows consoles, e.g. powershell terminal v5.x

added call to colorama just_fix_windows_console()
